# datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.200.128:3306/mp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 528528
    driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl